# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class AstroPaperStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getWallpaper = channel.unary_unary(
        '/AstroPaper.AstroPaper/getWallpaper',
        request_serializer=api__pb2.Empty.SerializeToString,
        response_deserializer=api__pb2.GetResponse.FromString,
        )
    self.setupWallpaper = channel.unary_unary(
        '/AstroPaper.AstroPaper/setupWallpaper',
        request_serializer=api__pb2.SetupRequest.SerializeToString,
        response_deserializer=api__pb2.SetupResponse.FromString,
        )


class AstroPaperServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getWallpaper(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setupWallpaper(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AstroPaperServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getWallpaper': grpc.unary_unary_rpc_method_handler(
          servicer.getWallpaper,
          request_deserializer=api__pb2.Empty.FromString,
          response_serializer=api__pb2.GetResponse.SerializeToString,
      ),
      'setupWallpaper': grpc.unary_unary_rpc_method_handler(
          servicer.setupWallpaper,
          request_deserializer=api__pb2.SetupRequest.FromString,
          response_serializer=api__pb2.SetupResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AstroPaper.AstroPaper', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
