# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apservice.proto',
  package='astropaperpackage',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61pservice.proto\x12\x11\x61stropaperpackage\"$\n\x10WallpaperRequest\x12\x10\n\x08quantity\x18\x01 \x01(\x05\"!\n\x0cSetupRequest\x12\x11\n\twallpaper\x18\x01 \x01(\t\"\x19\n\x08\x41PIReply\x12\r\n\x05reply\x18\x01 \x01(\t2\xb5\x01\n\nAstropaper\x12U\n\x0fGetNewWallpaper\x12#.astropaperpackage.WallpaperRequest\x1a\x1b.astropaperpackage.APIReply\"\x00\x12P\n\x0eSetupWallpaper\x12\x1f.astropaperpackage.SetupRequest\x1a\x1b.astropaperpackage.APIReply\"\x00\x62\x06proto3')
)




_WALLPAPERREQUEST = _descriptor.Descriptor(
  name='WallpaperRequest',
  full_name='astropaperpackage.WallpaperRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='astropaperpackage.WallpaperRequest.quantity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=74,
)


_SETUPREQUEST = _descriptor.Descriptor(
  name='SetupRequest',
  full_name='astropaperpackage.SetupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wallpaper', full_name='astropaperpackage.SetupRequest.wallpaper', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=109,
)


_APIREPLY = _descriptor.Descriptor(
  name='APIReply',
  full_name='astropaperpackage.APIReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='astropaperpackage.APIReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['WallpaperRequest'] = _WALLPAPERREQUEST
DESCRIPTOR.message_types_by_name['SetupRequest'] = _SETUPREQUEST
DESCRIPTOR.message_types_by_name['APIReply'] = _APIREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WallpaperRequest = _reflection.GeneratedProtocolMessageType('WallpaperRequest', (_message.Message,), dict(
  DESCRIPTOR = _WALLPAPERREQUEST,
  __module__ = 'apservice_pb2'
  # @@protoc_insertion_point(class_scope:astropaperpackage.WallpaperRequest)
  ))
_sym_db.RegisterMessage(WallpaperRequest)

SetupRequest = _reflection.GeneratedProtocolMessageType('SetupRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETUPREQUEST,
  __module__ = 'apservice_pb2'
  # @@protoc_insertion_point(class_scope:astropaperpackage.SetupRequest)
  ))
_sym_db.RegisterMessage(SetupRequest)

APIReply = _reflection.GeneratedProtocolMessageType('APIReply', (_message.Message,), dict(
  DESCRIPTOR = _APIREPLY,
  __module__ = 'apservice_pb2'
  # @@protoc_insertion_point(class_scope:astropaperpackage.APIReply)
  ))
_sym_db.RegisterMessage(APIReply)



_ASTROPAPER = _descriptor.ServiceDescriptor(
  name='Astropaper',
  full_name='astropaperpackage.Astropaper',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=139,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNewWallpaper',
    full_name='astropaperpackage.Astropaper.GetNewWallpaper',
    index=0,
    containing_service=None,
    input_type=_WALLPAPERREQUEST,
    output_type=_APIREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetupWallpaper',
    full_name='astropaperpackage.Astropaper.SetupWallpaper',
    index=1,
    containing_service=None,
    input_type=_SETUPREQUEST,
    output_type=_APIREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASTROPAPER)

DESCRIPTOR.services_by_name['Astropaper'] = _ASTROPAPER

# @@protoc_insertion_point(module_scope)
