# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import astropaperservice_pb2 as astropaperservice__pb2


class AstroPaperServiceStub(object):
  """The api service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNewWallpaper = channel.unary_unary(
        '/astropaper.AstroPaperService/GetNewWallpaper',
        request_serializer=astropaperservice__pb2.WallpaperRequest.SerializeToString,
        response_deserializer=astropaperservice__pb2.APIReply.FromString,
        )
    self.SetupWallpaper = channel.unary_unary(
        '/astropaper.AstroPaperService/SetupWallpaper',
        request_serializer=astropaperservice__pb2.SetupRequest.SerializeToString,
        response_deserializer=astropaperservice__pb2.APIReply.FromString,
        )


class AstroPaperServiceServicer(object):
  """The api service definition.
  """

  def GetNewWallpaper(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetupWallpaper(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AstroPaperServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNewWallpaper': grpc.unary_unary_rpc_method_handler(
          servicer.GetNewWallpaper,
          request_deserializer=astropaperservice__pb2.WallpaperRequest.FromString,
          response_serializer=astropaperservice__pb2.APIReply.SerializeToString,
      ),
      'SetupWallpaper': grpc.unary_unary_rpc_method_handler(
          servicer.SetupWallpaper,
          request_deserializer=astropaperservice__pb2.SetupRequest.FromString,
          response_serializer=astropaperservice__pb2.APIReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'astropaper.AstroPaperService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
