# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='AstroPaper',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\nAstroPaper\"\x16\n\x05\x45mpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\t\"\x1b\n\x0bGetResponse\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"\x1c\n\x0cSetupRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\" \n\rSetupResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x93\x01\n\nAstroPaper\x12<\n\x0cgetWallpaper\x12\x11.AstroPaper.Empty\x1a\x17.AstroPaper.GetResponse\"\x00\x12G\n\x0esetupWallpaper\x12\x18.AstroPaper.SetupRequest\x1a\x19.AstroPaper.SetupResponse\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='AstroPaper.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='AstroPaper.Empty.empty', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=47,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='AstroPaper.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='AstroPaper.GetResponse.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)


_SETUPREQUEST = _descriptor.Descriptor(
  name='SetupRequest',
  full_name='AstroPaper.SetupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='AstroPaper.SetupRequest.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=106,
)


_SETUPRESPONSE = _descriptor.Descriptor(
  name='SetupResponse',
  full_name='AstroPaper.SetupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='AstroPaper.SetupResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.message_types_by_name['SetupRequest'] = _SETUPREQUEST
DESCRIPTOR.message_types_by_name['SetupResponse'] = _SETUPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:AstroPaper.Empty)
  ))
_sym_db.RegisterMessage(Empty)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:AstroPaper.GetResponse)
  ))
_sym_db.RegisterMessage(GetResponse)

SetupRequest = _reflection.GeneratedProtocolMessageType('SetupRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETUPREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:AstroPaper.SetupRequest)
  ))
_sym_db.RegisterMessage(SetupRequest)

SetupResponse = _reflection.GeneratedProtocolMessageType('SetupResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETUPRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:AstroPaper.SetupResponse)
  ))
_sym_db.RegisterMessage(SetupResponse)



_ASTROPAPER = _descriptor.ServiceDescriptor(
  name='AstroPaper',
  full_name='AstroPaper.AstroPaper',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=143,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='getWallpaper',
    full_name='AstroPaper.AstroPaper.getWallpaper',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setupWallpaper',
    full_name='AstroPaper.AstroPaper.setupWallpaper',
    index=1,
    containing_service=None,
    input_type=_SETUPREQUEST,
    output_type=_SETUPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASTROPAPER)

DESCRIPTOR.services_by_name['AstroPaper'] = _ASTROPAPER

# @@protoc_insertion_point(module_scope)
