# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astropaperservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='astropaperservice.proto',
  package='astropaper',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x61stropaperservice.proto\x12\nastropaper\"\x1a\n\nAPIRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x08\x41PIReply\x12\r\n\x05reply\x18\x01 \x01(\t2\x98\x01\n\x11\x41stroPaperService\x12\x41\n\x0fGetNewWallpaper\x12\x16.astropaper.APIRequest\x1a\x14.astropaper.APIReply\"\x00\x12@\n\x0eSetupWallpaper\x12\x16.astropaper.APIRequest\x1a\x14.astropaper.APIReply\"\x00\x62\x06proto3')
)




_APIREQUEST = _descriptor.Descriptor(
  name='APIRequest',
  full_name='astropaper.APIRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='astropaper.APIRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=65,
)


_APIREPLY = _descriptor.Descriptor(
  name='APIReply',
  full_name='astropaper.APIReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='astropaper.APIReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['APIRequest'] = _APIREQUEST
DESCRIPTOR.message_types_by_name['APIReply'] = _APIREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

APIRequest = _reflection.GeneratedProtocolMessageType('APIRequest', (_message.Message,), dict(
  DESCRIPTOR = _APIREQUEST,
  __module__ = 'astropaperservice_pb2'
  # @@protoc_insertion_point(class_scope:astropaper.APIRequest)
  ))
_sym_db.RegisterMessage(APIRequest)

APIReply = _reflection.GeneratedProtocolMessageType('APIReply', (_message.Message,), dict(
  DESCRIPTOR = _APIREPLY,
  __module__ = 'astropaperservice_pb2'
  # @@protoc_insertion_point(class_scope:astropaper.APIReply)
  ))
_sym_db.RegisterMessage(APIReply)



_ASTROPAPERSERVICE = _descriptor.ServiceDescriptor(
  name='AstroPaperService',
  full_name='astropaper.AstroPaperService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=95,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNewWallpaper',
    full_name='astropaper.AstroPaperService.GetNewWallpaper',
    index=0,
    containing_service=None,
    input_type=_APIREQUEST,
    output_type=_APIREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetupWallpaper',
    full_name='astropaper.AstroPaperService.SetupWallpaper',
    index=1,
    containing_service=None,
    input_type=_APIREQUEST,
    output_type=_APIREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASTROPAPERSERVICE)

DESCRIPTOR.services_by_name['AstroPaperService'] = _ASTROPAPERSERVICE

# @@protoc_insertion_point(module_scope)
